import { NextResponse } from "next/server";
import prisma from "@/shared/lib/prisma";
import { randomBytes } from "crypto";
import Logger from "@/shared/lib/logger";

const log = Logger.get("API:EventCreate");

// Intent: Generate a short, URL-friendly unique identifier (8 characters).
function generateSlug() {
    return randomBytes(4).toString("hex"); // e.g., "a1b2c3d4"
}

/**
 * @function POST
 * @description Creates a new event with initial time slots.
 *
 * Flow:
 * 1. Validates payload (title, slots, minPlayers).
 * 2. Generates a unique `slug` for public URL access.
 * 3. Creates the Event and associated TimeSlots transactionally in Postgres.
 * 4. Returns the sensitive `adminToken` (generated by Prisma default constraint or middleware) 
 *    so the frontend can set the management cookie immediately.
 *
 * @param {Request} req - JSON Payload: { title, description, minPlayers, slots: [{startTime, endTime}], telegramLink, timezone }
 * @returns {NextResponse} JSON with { slug, id, adminToken }.
 */
export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { title, description, minPlayers, maxPlayers, slots, telegramLink } = body;

        log.debug("Request received", { title });

        if (!title || !slots || !Array.isArray(slots) || slots.length === 0) {
            log.warn("Invalid payload", { title, slotsLength: slots?.length });
            return NextResponse.json({ error: "Invalid data" }, { status: 400 });
        }

        const slug = generateSlug();

        // Security: Generate token manually so we can hash it for storage.
        const { randomUUID } = await import("crypto");
        const { hashToken } = await import("@/shared/lib/token");

        const rawAdminToken = randomUUID();
        const hashedAdminToken = hashToken(rawAdminToken);

        // Action: transactional creation ensures we don't have an event without slots.
        // Extended Logic: Webhook Callback
        const { fromUrl, fromUrlId } = body;

        // Action: transactional creation ensures we don't have an event without slots.
        // Prisma transaction is extended to include Webhook creation if needed.
        const event = await prisma.$transaction(async (tx) => {
            const newEvent = await tx.event.create({
                data: {
                    slug,
                    title,
                    description,
                    adminToken: hashedAdminToken, // Store Hash
                    telegramLink,
                    timezone: body.timezone || "UTC",
                    minPlayers: minPlayers || 3,
                    maxPlayers: maxPlayers || null,
                    status: "DRAFT",
                    fromUrl: fromUrl || null,
                    fromUrlId: fromUrlId || null,
                    timeSlots: {
                        create: slots.map((slot: any) => ({
                            startTime: new Date(slot.startTime),
                            endTime: new Date(slot.endTime),
                        })),
                    },
                },
            });

            // If external URL provided, enqueue the webhook task immediately
            if (fromUrl) {
                const { getBaseUrl } = await import("@/shared/lib/url");
                const origin = getBaseUrl(req.headers);
                const votingLink = `${origin}/e/${slug}`;

                await tx.webhookEvent.create({
                    data: {
                        eventId: newEvent.id,
                        url: fromUrl,
                        status: "PENDING",
                        nextAttempt: new Date(), // Process immediately
                        payload: JSON.stringify({
                            type: "CREATED",
                            eventId: newEvent.id,
                            fromUrlId: fromUrlId || null,
                            slug: newEvent.slug,
                            link: votingLink,
                            title: newEvent.title,
                            timestamp: new Date().toISOString()
                        })
                    }
                });
            }

            return newEvent;
        });

        log.info("Event created successfully", { slug, id: event.id, hasWebhook: !!fromUrl });
        // Return Plaintext to user
        return NextResponse.json({ slug: event.slug, id: event.id, adminToken: rawAdminToken });
    } catch (error) {
        log.error("Failed to create event", error as Error);
        return NextResponse.json(
            { error: "Internal Server Error" },
            { status: 500 }
        );
    }
}
