import { NextResponse } from "next/server";
import prisma from "@/shared/lib/prisma";
import { randomBytes } from "crypto";
import Logger from "@/shared/lib/logger";

const log = Logger.get("API:EventCreate");

// Intent: Generate a short, URL-friendly unique identifier (8 characters).
function generateSlug() {
    return randomBytes(4).toString("hex"); // e.g., "a1b2c3d4"
}

/**
 * @function POST
 * @description Creates a new event with initial time slots.
 *
 * Flow:
 * 1. Validates payload (title, slots, minPlayers).
 * 2. Generates a unique `slug` for public URL access.
 * 3. Creates the Event and associated TimeSlots transactionally in Postgres.
 * 4. Returns the sensitive `adminToken` (generated by Prisma default constraint or middleware) 
 *    so the frontend can set the management cookie immediately.
 *
 * @param {Request} req - JSON Payload: { title, description, minPlayers, slots: [{startTime, endTime}], telegramLink, timezone }
 * @returns {NextResponse} JSON with { slug, id, adminToken }.
 */
export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { title, description, minPlayers, maxPlayers, slots, telegramLink } = body;

        log.debug("Request received", { title });

        if (!title || !slots || !Array.isArray(slots) || slots.length === 0) {
            log.warn("Invalid payload", { title, slotsLength: slots?.length });
            return NextResponse.json({ error: "Invalid data" }, { status: 400 });
        }

        const slug = generateSlug();

        // Action: transactional creation ensures we don't have an event without slots.
        const event = await prisma.event.create({
            data: {
                slug,
                title,
                description,
                telegramLink,
                timezone: body.timezone || "UTC",
                minPlayers: minPlayers || 3,
                maxPlayers: maxPlayers || null,
                status: "DRAFT",
                timeSlots: {
                    create: slots.map((slot: any) => ({
                        startTime: new Date(slot.startTime),
                        endTime: new Date(slot.endTime),
                    })),
                },
            },
        });

        log.info("Event created successfully", { slug, id: event.id });
        return NextResponse.json({ slug: event.slug, id: event.id, adminToken: event.adminToken });
    } catch (error) {
        log.error("Failed to create event", error as Error);
        return NextResponse.json(
            { error: "Internal Server Error" },
            { status: 500 }
        );
    }
}
