name: 🐛 Bug Report
description: Create a report to help us improve.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: deployment_mode
    attributes:
      label: Deployment Mode
      description: How are you running the application?
      options:
        - Docker (Self-Hosted)
        - Vercel / Cloud Hosted
        - Local Development (npm run dev)
        - Other
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Please provide details about your setup.
        - OS (e.g. Ubuntu 22.04, Windows 11)
        - Browser (if UI issue)
        - Node Version (if applicable)
      placeholder: "OS: Ubuntu 22.04\nBrowser: Chrome 120"
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How critical is this issue?
      options:
        - 🔴 Critical (System Down / Data Loss)
        - 🟡 Major (Feature Broken)
        - 🟢 Minor (Visual / Annoyance)
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: textarea
    id: logs
    attributes:
      label: Logs / Output
      description: |
        Please paste any relevant logs.
        For Docker: `docker logs <container_id>`
    render: Request
