import { describe, it, expect } from 'vitest';
import { renderModule, resolveCutoff, resolveMode, selectPosts } from './generate-published-posts.mjs';

const post = (title: string, date: string, extra: string[] = []) =>
    ['---', `title: "${title}"`, `date: "${date}"`, ...extra, '---', `${title} body`].join('\n');

const files = {
    'past.md': post('Past', '2020-01-06'),
    'today.md': post('Today', '2026-10-04'),
    'future.md': post('Future', '2999-01-06'),
    'draft.md': post('Draft', '2020-01-06', ['draft: true']),
    'undated.md': ['---', 'title: "Undated"', '---', 'Undated body'].join('\n'),
    'notes.txt': 'ignored',
};

const off = { showScheduled: false, showDrafts: false };
const cutoff = Date.parse('2026-10-04');
const slugs = (result: { posts: { slug: string }[] }) => result.posts.map((p) => p.slug);

describe('selectPosts', () => {
    it('keeps past, same-day and undated posts, holds back future and draft posts', () => {
        const result = selectPosts(files, { cutoff, mode: off, now: cutoff });
        expect(slugs(result)).toEqual(['undated', 'today', 'past']);
        expect(result.heldBack).toBe(2);
    });

    it('applies BUILD_DATE as the cutoff', () => {
        const before = selectPosts(files, { cutoff: resolveCutoff({ BUILD_DATE: '2026-10-03' }), mode: off });
        expect(slugs(before)).not.toContain('today');
        const after = selectPosts(files, { cutoff: resolveCutoff({ BUILD_DATE: '2999-01-06' }), mode: off });
        expect(slugs(after)).toContain('future');
        expect(slugs(after)).not.toContain('draft');
    });

    it('includes scheduled posts only when showScheduled is on', () => {
        const result = selectPosts(files, { cutoff, mode: { showScheduled: true, showDrafts: false } });
        expect(slugs(result)).toContain('future');
        expect(slugs(result)).not.toContain('draft');
    });

    it('includes drafts only when showDrafts is on', () => {
        const result = selectPosts(files, { cutoff, mode: { showScheduled: false, showDrafts: true } });
        expect(slugs(result)).toContain('draft');
        expect(slugs(result)).not.toContain('future');
    });
});

describe('resolveMode', () => {
    it('honours the preview flags for a plain --dev run', () => {
        expect(resolveMode({ SHOW_SCHEDULED: '1', SHOW_DRAFTS: '1' }, ['--dev'])).toEqual({
            showScheduled: true,
            showDrafts: true,
            ignoredFlags: false,
        });
        expect(resolveMode({ BLOG_SHOW_SCHEDULED: '1' }, ['--dev']).showScheduled).toBe(true);
    });

    it('ignores the flags without --dev', () => {
        const mode = resolveMode({ SHOW_SCHEDULED: '1' }, []);
        expect(mode).toEqual({ showScheduled: false, showDrafts: false, ignoredFlags: true });
    });

    it.each([['NODE_ENV', 'production'], ['VERCEL_ENV', 'production'], ['CI', 'true'], ['WORKERS_CI', '1']])(
        'ignores the flags when %s=%s',
        (key, value) => {
            const mode = resolveMode({ SHOW_SCHEDULED: '1', SHOW_DRAFTS: '1', [key]: value }, ['--dev']);
            expect(mode).toEqual({ showScheduled: false, showDrafts: false, ignoredFlags: true });
        },
    );
});

describe('renderModule', () => {
    it('emits a generated-file header and the posts', () => {
        const out = renderModule(selectPosts(files, { cutoff, mode: off }).posts);
        expect(out).toContain('GENERATED by scripts/generate-published-posts.mjs');
        expect(out).toContain('"slug": "past"');
        expect(out).not.toContain('"slug": "future"');
    });
});
